#! /bin/bash

prog='prog.py'
filename=''

while getopts 'f:m' flag; do
    case "${flag}" in
        f) filename="${OPTARG}" ;;
        m) prog='multi_prog.py' ;;
        *) error "unexpected" ;;
    esac
done

time python3.4 $prog testdata/$filename/sig.py testdata/$filename/data -fs 10000000
