
# /afs/cs.wisc.edu/u/c/j/cjsmith/summer/map-reduce-synth/takethree/typetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'F8E2434465DF190592FED91CF19A24CE'
    
_lr_action_items = {'BASE':([0,5,8,18,19,21,],[1,1,1,1,1,1,]),'TO':([1,2,3,6,7,10,12,13,14,17,20,23,24,25,26,27,],[-16,-7,-12,18,-11,-8,-17,-9,-10,18,18,-14,18,18,-6,18,]),'CLOSE':([1,2,3,7,10,12,13,14,20,23,24,25,26,],[-16,-7,-12,-11,-8,-17,-9,-10,26,-14,-13,-15,-6,]),'DOT':([12,15,16,28,],[-17,21,-4,-5,]),'OPENLIST':([0,5,8,18,19,21,],[5,5,5,5,5,5,]),'QUANT':([0,],[4,]),'OPEN':([0,5,8,18,19,21,],[8,8,8,8,8,8,]),'COMMA':([1,2,3,6,7,10,12,13,14,16,17,20,23,24,25,26,27,],[-16,-7,-12,19,-11,-8,-17,-9,-10,22,19,19,-14,19,19,-6,19,]),'VAR':([0,4,5,8,18,19,21,22,],[12,12,12,12,12,12,12,12,]),'CLOSELIST':([1,2,3,7,10,12,13,14,17,23,24,25,26,],[-16,-7,-12,-11,-8,-17,-9,-10,23,-14,-13,-15,-6,]),'$end':([1,2,3,6,7,9,10,11,12,13,14,23,24,25,26,27,],[-16,-7,-12,-1,-11,0,-8,-2,-17,-9,-10,-14,-13,-15,-6,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'base':([0,5,8,18,19,21,],[2,2,2,2,2,2,]),'pair':([0,5,8,18,19,21,],[3,3,3,3,3,3,]),'varlist':([4,22,],[15,28,]),'var':([0,4,5,8,18,19,21,22,],[10,16,10,10,10,10,10,16,]),'poly':([0,],[11,]),'mono':([0,5,8,18,19,21,],[6,17,20,24,25,27,]),'list':([0,5,8,18,19,21,],[7,7,7,7,7,7,]),'function':([0,5,8,18,19,21,],[14,14,14,14,14,14,]),'constructor':([0,5,8,18,19,21,],[13,13,13,13,13,13,]),'type':([0,],[9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> type","S'",1,None,None,None),
  ('type -> mono','type',1,'p_type','components.py',35),
  ('type -> poly','type',1,'p_type','components.py',36),
  ('poly -> QUANT varlist DOT mono','poly',4,'p_poly','components.py',40),
  ('varlist -> var','varlist',1,'p_varlist','components.py',44),
  ('varlist -> var COMMA varlist','varlist',3,'p_varlist','components.py',45),
  ('mono -> OPEN mono CLOSE','mono',3,'p_mono','components.py',52),
  ('mono -> base','mono',1,'p_mono','components.py',53),
  ('mono -> var','mono',1,'p_mono','components.py',54),
  ('mono -> constructor','mono',1,'p_mono','components.py',55),
  ('constructor -> function','constructor',1,'p_constructor','components.py',62),
  ('constructor -> list','constructor',1,'p_constructor','components.py',63),
  ('constructor -> pair','constructor',1,'p_constructor','components.py',64),
  ('function -> mono TO mono','function',3,'p_function','components.py',68),
  ('list -> OPENLIST mono CLOSELIST','list',3,'p_list','components.py',72),
  ('pair -> mono COMMA mono','pair',3,'p_pair','components.py',76),
  ('base -> BASE','base',1,'p_base','components.py',80),
  ('var -> VAR','var',1,'p_var','components.py',86),
]
